
# source files in this project (main.cpp is automatically assumed)
SOURCES := 

# header files in this project
HEADERS := GameControl.hpp Objects.hpp Statemachine.hpp SplashScreen.hpp MainMenu.hpp LeaderBoard.hpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.native